name: Deployment project
on: push
jobs:
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #     - name: Install Node js
  #       uses: actions/setup-node@v4
  #     - name: Install Dependencies
  #       run: npm ci
  #     - name: Run test-cases
  #       run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Install Dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Deploy code
        run: echo "Build Successful"
